DROP TABLE alunos CASCADE CONSTRAINTS;
DROP TABLE cursos CASCADE CONSTRAINTS;
DROP TABLE departamentos CASCADE CONSTRAINTS;
DROP TABLE disciplinas CASCADE CONSTRAINTS;
DROP TABLE matriculas CASCADE CONSTRAINTS;
DROP TABLE matrizes_cursos CASCADE CONSTRAINTS;
