DROP TABLE dim_curso CASCADE CONSTRAINTS;
DROP TABLE dim_departamento CASCADE CONSTRAINTS;
DROP TABLE dim_disciplina CASCADE CONSTRAINTS;
DROP TABLE dim_tempo CASCADE CONSTRAINTS;
DROP TABLE fact_reprovacao CASCADE CONSTRAINTS;